"""Embedded-thumbnail comparison. Pure, deterministic; no I/O beyond in-memory decoding.

Cameras and many editors store a small JPEG preview in the EXIF block (IFD1). Editors that
change pixels without regenerating that preview leave a thumbnail that still shows the
*earlier* picture: a cropped, flipped, or locally altered image then disagrees with its own
thumbnail. The comparison is a heuristic: thumbnails are made by different pipelines
(sharpening, tone curves, letterboxing), some cameras store a slightly different framing,
and a resave regenerates the thumbnail and erases the trace. Results are POSSIBLE at most.
"""

import io
import struct
from dataclasses import dataclass, field
from typing import Any

import numpy as np
from numpy.typing import NDArray
from PIL import Image

from app.services.image.regions import Region, connected_regions

THUMBNAIL_VERSION = "v1"
METHOD = "thumbnail"
EMBEDDED_ARTIFACT_METHOD = "thumbnail_embedded"

# EXIF thumbnails live in TIFF-structured blocks: JPEG APP1 and TIFF files.
APPLICABLE_FORMATS = frozenset({"JPEG", "TIFF"})

_JPEG_INTERCHANGE = 0x0201
_JPEG_INTERCHANGE_LENGTH = 0x0202
_MAX_THUMBNAIL_BYTES = 4 * 1024 * 1024
MIN_THUMBNAIL_SIDE = 16
# Blocks whose mean normalised difference is below this never count as outliers.
MIN_OUTLIER_LEVEL = 0.35
MIN_REGION_BLOCKS = 2
MAX_REGIONS = 8
# A transform must beat the plain comparison by this much (and be good) to count as a flip.
TRANSFORM_MARGIN = 0.15
TRANSFORM_MIN_CORRELATION = 0.85

LIMITATIONS = [
    "Thumbnails are generated by a different pipeline than the main image (tone curve, "
    "sharpening, subsampling, sometimes letterboxing), so small differences are normal.",
    "Any full resave regenerates the thumbnail and erases the trace; a matching thumbnail "
    "says nothing about edits made before the last save.",
    "Some cameras and phones store a thumbnail with a slightly different framing or "
    "orientation than the final image.",
    "The comparison runs at thumbnail resolution, so small edits are below its reach.",
]

NOT_APPLICABLE_REASON = "This file format carries no EXIF block, so there is no embedded thumbnail."
NO_THUMBNAIL_REASON = "The file has no embedded EXIF thumbnail to compare against."


@dataclass(frozen=True)
class ThumbnailResult:
    thumbnail_width: int
    thumbnail_height: int
    original_width: int
    original_height: int
    aspect_ratio_thumbnail: float
    aspect_ratio_image: float
    aspect_mismatch: bool
    correlation: float
    correlation_outside_regions: float
    best_transform: str  # "none" | "flip_h" | "flip_v" | "rotate_180"
    best_transform_correlation: float
    orientation_mismatch: bool
    block_size: int
    outlier_sigma: float
    outlier_block_fraction: float
    regions: list[Region]
    mismatch_global: bool
    anomaly: bool
    observation: str
    # Difference map (thumbnail scale, enlarged) and the decoded embedded thumbnail.
    visualization_png: bytes = field(repr=False)
    thumbnail_png: bytes = field(repr=False)
    limitations: list[str] = field(default_factory=lambda: list(LIMITATIONS))
    confidence: str = "low"

    @property
    def flagged(self) -> bool:
        return (
            self.anomaly
            or self.mismatch_global
            or self.aspect_mismatch
            or self.orientation_mismatch
        )

    def to_json(self) -> dict[str, Any]:
        return {
            "method": METHOD,
            "version": THUMBNAIL_VERSION,
            "applicable": True,
            "has_thumbnail": True,
            "thumbnail_width": self.thumbnail_width,
            "thumbnail_height": self.thumbnail_height,
            "original_width": self.original_width,
            "original_height": self.original_height,
            "aspect_ratio_thumbnail": self.aspect_ratio_thumbnail,
            "aspect_ratio_image": self.aspect_ratio_image,
            "aspect_mismatch": self.aspect_mismatch,
            "correlation": self.correlation,
            "correlation_outside_regions": self.correlation_outside_regions,
            "best_transform": self.best_transform,
            "best_transform_correlation": self.best_transform_correlation,
            "orientation_mismatch": self.orientation_mismatch,
            "block_size": self.block_size,
            "outlier_sigma": self.outlier_sigma,
            "outlier_block_fraction": self.outlier_block_fraction,
            "regions": [r.to_json("mean_diff") for r in self.regions],
            "mismatch_global": self.mismatch_global,
            "anomaly": self.anomaly,
            "flagged": self.flagged,
            "confidence": self.confidence,
            "observation": self.observation,
            "limitations": list(self.limitations),
        }


def not_applicable_json(reason: str, *, pil_format: str | None = None) -> dict[str, Any]:
    out: dict[str, Any] = {
        "method": METHOD,
        "version": THUMBNAIL_VERSION,
        "applicable": False,
        "has_thumbnail": False,
        "reason": reason,
        "limitations": list(LIMITATIONS),
    }
    if pil_format:
        out["format"] = pil_format
    return out


# -- EXIF thumbnail extraction -----------------------------------------------------------------


def _tiff_block(data: bytes) -> bytes | None:
    """The TIFF-structured EXIF block: the file itself for TIFF, the APP1 payload for JPEG."""
    if data[:4] in (b"II*\x00", b"MM\x00*"):
        return data
    if data[:2] != b"\xff\xd8":
        return None
    pos = 2
    while pos + 4 <= len(data):
        if data[pos] != 0xFF:
            return None
        marker = data[pos + 1]
        if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:  # standalone markers
            pos += 2
            continue
        if marker in (0xDA, 0xD9):  # start of scan / end of image: no more headers
            return None
        (length,) = struct.unpack(">H", data[pos + 2 : pos + 4])
        segment = data[pos + 4 : pos + 2 + length]
        if marker == 0xE1 and segment.startswith(b"Exif\x00\x00"):
            return segment[6:]
        pos += 2 + length
    return None


def extract_exif_thumbnail(data: bytes) -> bytes | None:
    """JPEG bytes of the IFD1 thumbnail, or None when absent or malformed. Never raises."""
    tiff = _tiff_block(data)
    if tiff is None or len(tiff) < 8:
        return None
    endian = "<" if tiff[:2] == b"II" else ">" if tiff[:2] == b"MM" else None
    if endian is None:
        return None
    try:
        (ifd0,) = struct.unpack(endian + "I", tiff[4:8])
        (count,) = struct.unpack(endian + "H", tiff[ifd0 : ifd0 + 2])
        next_ptr = ifd0 + 2 + 12 * count
        (ifd1,) = struct.unpack(endian + "I", tiff[next_ptr : next_ptr + 4])
        if ifd1 == 0 or ifd1 + 2 > len(tiff):
            return None
        (count1,) = struct.unpack(endian + "H", tiff[ifd1 : ifd1 + 2])
        offset = length = None
        for i in range(count1):
            entry = tiff[ifd1 + 2 + 12 * i : ifd1 + 14 + 12 * i]
            if len(entry) < 12:
                return None
            tag, typ, n = struct.unpack(endian + "HHI", entry[:8])
            if typ == 4 and n == 1:  # LONG
                (value,) = struct.unpack(endian + "I", entry[8:12])
            elif typ == 3 and n == 1:  # SHORT
                (value,) = struct.unpack(endian + "H", entry[8:10])
            else:
                continue
            if tag == _JPEG_INTERCHANGE:
                offset = value
            elif tag == _JPEG_INTERCHANGE_LENGTH:
                length = value
    except struct.error:
        return None
    if offset is None or length is None or length <= 0 or length > _MAX_THUMBNAIL_BYTES:
        return None
    blob = tiff[offset : offset + length]
    return blob if blob[:2] == b"\xff\xd8" and len(blob) == length else None


# -- comparison ---------------------------------------------------------------------------------


def _gray(img: Image.Image) -> NDArray[np.float32]:
    arr = np.asarray(img.convert("L"), dtype=np.float32)
    # 3x3 mean blur damps JPEG noise at thumbnail scale.
    padded = np.pad(arr, 1, mode="edge")
    acc = np.zeros_like(arr)
    for dy in (0, 1, 2):
        for dx in (0, 1, 2):
            acc += padded[dy : dy + arr.shape[0], dx : dx + arr.shape[1]]
    return acc / 9.0


def _normalised(arr: NDArray[np.float32]) -> NDArray[np.float32]:
    std = float(arr.std())
    return (arr - float(arr.mean())) / (std if std > 1e-6 else 1.0)


def _correlation(a: NDArray[np.float32], b: NDArray[np.float32]) -> float:
    an, bn = _normalised(a), _normalised(b)
    return float(np.clip((an * bn).mean(), -1.0, 1.0))


def _block_means(err: NDArray[np.float32], block: int) -> NDArray[np.float32]:
    h, w = err.shape
    bh, bw = -(-h // block), -(-w // block)
    padded = np.zeros((bh * block, bw * block), dtype=np.float32)
    padded[:h, :w] = err
    ones = np.zeros_like(padded)
    ones[:h, :w] = 1
    sums = padded.reshape(bh, block, bw, block).sum(axis=(1, 3))
    counts = ones.reshape(bh, block, bw, block).sum(axis=(1, 3))
    return np.asarray(sums / np.maximum(counts, 1), dtype=np.float32)


def _observation(r: dict[str, Any]) -> str:
    parts: list[str] = []
    if r["mismatch_global"]:
        parts.append(
            "The embedded thumbnail does not depict the current image content "
            f"(correlation {r['correlation']:.2f}). Either the picture was replaced or heavily "
            "edited after the thumbnail was made, or the thumbnail belongs to another file."
        )
    elif r["anomaly"]:
        parts.append(
            f"{r['regions']} localised region(s) differ from the embedded thumbnail while the rest "
            f"of the picture matches it (correlation {r['correlation']:.2f}); consistent with a "
            "local edit made after the thumbnail was generated."
        )
    else:
        parts.append(
            "The embedded thumbnail matches the current image (correlation "
            f"{r['correlation']:.2f}); no localised difference stands out."
        )
    if r["orientation_mismatch"]:
        parts.append(
            f"The image matches its thumbnail best after a {r['best_transform']} transform, so it "
            "was probably flipped or rotated after the thumbnail was made."
        )
    if r["aspect_mismatch"]:
        parts.append(
            f"Aspect ratios differ (image {r['aspect_ratio_image']:.3f}, thumbnail "
            f"{r['aspect_ratio_thumbnail']:.3f}), which is what cropping after the thumbnail "
            "was made looks like; some cameras also frame thumbnails differently."
        )
    return " ".join(parts)


def compare_thumbnail(
    data: bytes,
    *,
    min_correlation: float = 0.9,
    outlier_sigma: float = 2.5,
    anomaly_min_fraction: float = 0.01,
    anomaly_max_fraction: float = 0.3,
    aspect_tolerance: float = 0.05,
) -> ThumbnailResult | None:
    """Compare the image with its EXIF thumbnail; None when there is no usable thumbnail."""
    thumb_bytes = extract_exif_thumbnail(data)
    if thumb_bytes is None:
        return None
    try:
        with Image.open(io.BytesIO(thumb_bytes)) as t:
            t.load()
            thumb = t.convert("RGB")
    except Exception:
        return None
    tw, th = thumb.size
    if min(tw, th) < MIN_THUMBNAIL_SIDE:
        return None
    with Image.open(io.BytesIO(data)) as img:
        img.load()
        ow, oh = img.size
        main = img.convert("RGB")

    aspect_t, aspect_i = tw / th, ow / oh
    aspect_mismatch = abs(aspect_t - aspect_i) / aspect_i > aspect_tolerance
    small = main.resize((tw, th), Image.Resampling.LANCZOS)
    g_thumb, g_main = _gray(thumb), _gray(small)
    correlation = _correlation(g_thumb, g_main)
    transforms = {
        "flip_h": np.fliplr(g_main),
        "flip_v": np.flipud(g_main),
        "rotate_180": np.rot90(g_main, 2),
    }
    best_transform, best_corr = "none", correlation
    for name, arr in transforms.items():
        c = _correlation(g_thumb, np.ascontiguousarray(arr))
        if c > best_corr:
            best_transform, best_corr = name, c
    orientation_mismatch = (
        best_transform != "none"
        and best_corr >= TRANSFORM_MIN_CORRELATION
        and best_corr - correlation >= TRANSFORM_MARGIN
    )

    diff = np.abs(_normalised(g_thumb) - _normalised(g_main)).astype(np.float32)
    block = max(4, min(tw, th) // 20)
    means = _block_means(diff, block)
    mu, sigma = float(means.mean()), float(means.std())
    mask = (means > mu + outlier_sigma * sigma) & (means > MIN_OUTLIER_LEVEL)
    fraction = float(mask.mean()) if mask.size else 0.0
    regions = connected_regions(
        mask,
        means,
        block=block,
        scale_x=ow / tw,
        scale_y=oh / th,
        min_blocks=MIN_REGION_BLOCKS,
        max_regions=MAX_REGIONS,
    )
    # A bright local edit drags the whole-image correlation down; judge "same picture" on the
    # pixels outside the outlier blocks so a local difference is not mistaken for a swap.
    if mask.any() and not mask.all():
        keep = ~np.kron(mask, np.ones((block, block), dtype=bool))[: diff.shape[0], : diff.shape[1]]
        correlation_rest = _correlation(g_thumb[keep], g_main[keep])
    else:
        correlation_rest = correlation
    mismatch_global = correlation_rest < min_correlation and not orientation_mismatch
    anomaly = (
        not mismatch_global
        and anomaly_min_fraction <= fraction <= anomaly_max_fraction
        and len(regions) > 0
    )

    # Difference map, enlarged with nearest-neighbour so blocks stay readable.
    p99 = float(np.percentile(diff, 99))
    vis = np.clip(diff * (255.0 / max(p99, 1e-3)), 0, 255).astype(np.uint8)
    scale = max(1, 640 // max(tw, th))
    vis_img = Image.fromarray(vis, mode="L").resize(
        (tw * scale, th * scale), Image.Resampling.NEAREST
    )
    out = io.BytesIO()
    vis_img.convert("RGB").save(out, format="PNG", optimize=True)
    thumb_out = io.BytesIO()
    thumb.save(thumb_out, format="PNG", optimize=True)

    fields: dict[str, Any] = {
        "mismatch_global": mismatch_global,
        "anomaly": anomaly,
        "regions": len(regions),
        "correlation": correlation,
        "orientation_mismatch": orientation_mismatch,
        "best_transform": best_transform,
        "aspect_mismatch": aspect_mismatch,
        "aspect_ratio_image": aspect_i,
        "aspect_ratio_thumbnail": aspect_t,
    }
    return ThumbnailResult(
        thumbnail_width=tw,
        thumbnail_height=th,
        original_width=ow,
        original_height=oh,
        aspect_ratio_thumbnail=round(aspect_t, 4),
        aspect_ratio_image=round(aspect_i, 4),
        aspect_mismatch=aspect_mismatch,
        correlation=round(correlation, 4),
        correlation_outside_regions=round(correlation_rest, 4),
        best_transform=best_transform,
        best_transform_correlation=round(best_corr, 4),
        orientation_mismatch=orientation_mismatch,
        block_size=block,
        outlier_sigma=outlier_sigma,
        outlier_block_fraction=round(fraction, 5),
        regions=regions,
        mismatch_global=mismatch_global,
        anomaly=anomaly,
        observation=_observation(fields),
        visualization_png=out.getvalue(),
        thumbnail_png=thumb_out.getvalue(),
    )
