"""Golden-value tests for content and perceptual hashes.

Fixtures live in tests/fixtures and are regenerated by make_fixtures.py; the
expected values below pin the algorithms so accidental changes are caught.
"""

import hashlib
import io
from pathlib import Path

import pytest
from PIL import Image

from app.services.image.hashing import (
    ImageHashes,
    average_hash,
    compute_hashes,
    difference_hash,
    hamming_distance,
    perceptual_hash,
)

FIXTURES = Path(__file__).parent / "fixtures"

GOLDEN: dict[str, dict[str, str]] = {
    "black.png": {
        "md5": "7a522d3d649e2c7bd84e8d6066b45732",
        "ahash": "0000000000000000",
        "dhash": "0000000000000000",
        "phash": "0000000000000000",
    },
    "gradient.png": {
        "md5": "cb1752036be9c277414ff78f89d11916",
        "ahash": "00003c3f3f3f0f0f",
        "dhash": "000c8e16168e8480",
        "phash": "9f423960e63fc21d",
    },
    "gradient_q60.jpg": {
        "md5": "9661d5e47fb5616d27c8e31f97482302",
        "ahash": "00003c3f3f3f0f0f",
        "dhash": "000c0e16168e8480",
        "phash": "9f423960e63fc21d",
    },
    "gradient_flipped.png": {
        "md5": "145afe7bdc199a8ebb601ea2ae332032",
        "ahash": "00003cfcfcfcf0f0",
        "dhash": "ffcd8e17978edcfe",
        "phash": "ca176c34b36a974a",
    },
    "half_black_white.png": {
        "md5": "25a5ff191dd552910c35490173bc249f",
        "ahash": "0f0f0f0f0f0f0f0f",
        "dhash": "2424242424242424",
        "phash": "93d94cb34cb3b164",
    },
}


def load(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


@pytest.mark.parametrize("name", sorted(GOLDEN))
def test_golden_values(name: str) -> None:
    data = load(name)
    h = compute_hashes(data)
    assert h.sha256 == hashlib.sha256(data).hexdigest()
    assert (h.md5, h.ahash, h.dhash, h.phash) == tuple(GOLDEN[name].values())
    for value in (h.ahash, h.dhash, h.phash):
        assert len(value) == 16 and int(value, 16) >= 0  # 64-bit hex


def test_hashes_are_deterministic() -> None:
    data = load("gradient.png")
    assert compute_hashes(data) == compute_hashes(data)


def test_recompression_keeps_perceptual_hashes_close() -> None:
    """Same picture as PNG and JPEG q60: bytes differ, perception barely does."""
    png, jpg = compute_hashes(load("gradient.png")), compute_hashes(load("gradient_q60.jpg"))
    assert png.sha256 != jpg.sha256 and png.md5 != jpg.md5
    assert hamming_distance(png.ahash, jpg.ahash) <= 2
    assert hamming_distance(png.dhash, jpg.dhash) <= 4
    assert hamming_distance(png.phash, jpg.phash) <= 4


def test_different_content_is_far_apart() -> None:
    g = compute_hashes(load("gradient.png"))
    flipped = compute_hashes(load("gradient_flipped.png"))
    black = compute_hashes(load("black.png"))
    # A mirror image is a different picture to these (non-symmetric) hashes.
    assert hamming_distance(g.phash, flipped.phash) >= 16
    assert hamming_distance(g.ahash, flipped.ahash) >= 16
    assert hamming_distance(g.phash, black.phash) >= 16


def test_half_image_average_hash_is_right_half_bright() -> None:
    # Left half black, right half white -> each row 00001111.
    with Image.open(FIXTURES / "half_black_white.png") as img:
        assert average_hash(img) == "0f" * 8


def test_uniform_image_hashes_to_zero() -> None:
    with Image.open(FIXTURES / "black.png") as img:
        assert average_hash(img) == difference_hash(img) == perceptual_hash(img) == "0" * 16
    with Image.new("RGB", (50, 30), (200, 200, 200)) as img:
        # pHash of a non-black flat image is dominated by float noise around the
        # DC term (same as reference implementations), so only aHash/dHash are pinned.
        assert average_hash(img) == difference_hash(img) == "0" * 16


def test_alpha_and_mode_do_not_change_result() -> None:
    base = Image.open(FIXTURES / "gradient.png").convert("RGB")
    rgba = base.convert("RGBA")
    assert perceptual_hash(base) == perceptual_hash(rgba)
    assert difference_hash(base) == difference_hash(rgba)


def test_hamming_distance() -> None:
    assert hamming_distance("0" * 16, "0" * 16) == 0
    assert hamming_distance("0" * 16, "f" * 16) == 64
    assert hamming_distance("8000000000000000", "0000000000000001") == 2
    with pytest.raises(ValueError):
        hamming_distance("00", "0000")


def test_compute_hashes_uses_first_frame_of_multi_frame_image() -> None:
    frames = [Image.new("L", (16, 16), 0), Image.new("L", (16, 16), 255)]
    buf = io.BytesIO()
    frames[0].save(buf, format="TIFF", save_all=True, append_images=frames[1:])
    h = compute_hashes(buf.getvalue())
    assert isinstance(h, ImageHashes)
    assert h.ahash == "0" * 16  # first frame is uniform black
