"""source matches

Revision ID: 3c7d15027a8f
Revises: 9a2ff4ab6f6f
Create Date: 2026-09-22 21:34:53.744422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3c7d15027a8f'
down_revision: Union[str, None] = '9a2ff4ab6f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reverse_matches',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_version', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('matched_phrase', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(length=64), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_reverse_matches_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reverse_matches'))
    )
    with op.batch_alter_table('reverse_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reverse_matches_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('source_search_runs',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_version', sa.String(length=64), nullable=False),
    sa.Column('queried_phrases_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('limitations_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_source_search_runs_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_search_runs')),
    sa.UniqueConstraint('analysis_id', name=op.f('uq_source_search_runs_analysis_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_search_runs')
    with op.batch_alter_table('reverse_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reverse_matches_analysis_id'))

    op.drop_table('reverse_matches')
    # ### end Alembic commands ###
