"""analysis files role

Revision ID: 5522ab366c39
Revises: 98b8a118f359
Create Date: 2026-10-04 23:22:40.291101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5522ab366c39'
down_revision: Union[str, None] = '98b8a118f359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=16), server_default='original', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_files', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
