"""forensics thumbnail and double compression

Revision ID: e04e4f5c5a56
Revises: 974ffa9044f1
Create Date: 2026-09-24 01:08:09.419136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e04e4f5c5a56'
down_revision: Union[str, None] = '974ffa9044f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_forensics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
        batch_op.add_column(sa.Column('double_compression_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_forensics', schema=None) as batch_op:
        batch_op.drop_column('double_compression_json')
        batch_op.drop_column('thumbnail_json')

    # ### end Alembic commands ###
