"""image provenance

Revision ID: c53b84bc6faf
Revises: 2cac9b8b6113
Create Date: 2026-09-22 16:20:41.409396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c53b84bc6faf'
down_revision: Union[str, None] = '2cac9b8b6113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_provenance',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('has_c2pa', sa.Boolean(), nullable=False),
    sa.Column('valid_signature', sa.Boolean(), nullable=True),
    sa.Column('signer', sa.String(length=300), nullable=True),
    sa.Column('signed_at', sa.String(length=64), nullable=True),
    sa.Column('claim_generator', sa.String(length=300), nullable=True),
    sa.Column('manifests_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('claims_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('normalized_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_image_provenance_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_provenance')),
    sa.UniqueConstraint('analysis_id', name=op.f('uq_image_provenance_analysis_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_provenance')
    # ### end Alembic commands ###
