"""usage

Revision ID: 974ffa9044f1
Revises: 19a3b8dca3fa
Create Date: 2026-09-23 02:18:47.403596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '974ffa9044f1'
down_revision: Union[str, None] = '19a3b8dca3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('analyses_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('text_count', sa.Integer(), nullable=False),
    sa.Column('reports_count', sa.Integer(), nullable=False),
    sa.Column('provider_calls_count', sa.Integer(), nullable=False),
    sa.Column('provider_cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage')),
    sa.UniqueConstraint('user_id', 'period_start', name='uq_usage_user_period')
    )
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_user_id'))

    op.drop_table('usage')
    # ### end Alembic commands ###
