"""image provenance trust

Revision ID: a8100edd051e
Revises: e04e4f5c5a56
Create Date: 2026-09-25 01:22:16.703417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8100edd051e'
down_revision: Union[str, None] = 'e04e4f5c5a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_provenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trusted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trust_list_version', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_provenance', schema=None) as batch_op:
        batch_op.drop_column('trust_list_version')
        batch_op.drop_column('trusted')

    # ### end Alembic commands ###
