"""ai detections

Revision ID: 9a2ff4ab6f6f
Revises: 0f78051be407
Create Date: 2026-09-22 21:21:53.148964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9a2ff4ab6f6f'
down_revision: Union[str, None] = '0f78051be407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_detections',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('provider_version', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('calibrated', sa.Boolean(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('threshold_high', sa.Float(), nullable=False),
    sa.Column('threshold_medium', sa.Float(), nullable=False),
    sa.Column('limitations_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_ai_detections_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_detections')),
    sa.UniqueConstraint('analysis_id', name=op.f('uq_ai_detections_analysis_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_detections')
    # ### end Alembic commands ###
