"""text fingerprints

Revision ID: 0f78051be407
Revises: d240bc2d6315
Create Date: 2026-09-22 21:04:36.854604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0f78051be407'
down_revision: Union[str, None] = 'd240bc2d6315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_fingerprints',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=False),
    sa.Column('canonical_sha256', sa.String(length=64), nullable=False),
    sa.Column('minhash_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('shingle_count', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_text_fingerprints_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text_fingerprints')),
    sa.UniqueConstraint('analysis_id', name=op.f('uq_text_fingerprints_analysis_id'))
    )
    with op.batch_alter_table('text_fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_fingerprints_canonical_sha256'), ['canonical_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_fingerprints_normalized_sha256'), ['normalized_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_fingerprints_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_fingerprints_sha256'))
        batch_op.drop_index(batch_op.f('ix_text_fingerprints_normalized_sha256'))
        batch_op.drop_index(batch_op.f('ix_text_fingerprints_canonical_sha256'))

    op.drop_table('text_fingerprints')
    # ### end Alembic commands ###
