"""forensics c2pa thumbnail

Revision ID: 98b8a118f359
Revises: a8100edd051e
Create Date: 2026-10-04 22:57:23.431203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '98b8a118f359'
down_revision: Union[str, None] = 'a8100edd051e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_forensics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c2pa_thumbnail_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_forensics', schema=None) as batch_op:
        batch_op.drop_column('c2pa_thumbnail_json')

    # ### end Alembic commands ###
