"""provider cache

Revision ID: adf632e6de85
Revises: 3c7d15027a8f
Create Date: 2026-09-22 22:12:23.567279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'adf632e6de85'
down_revision: Union[str, None] = '3c7d15027a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_cache')),
    sa.UniqueConstraint('cache_key', name=op.f('uq_provider_cache_cache_key'))
    )
    with op.batch_alter_table('provider_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_cache_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_cache_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_provider_cache_content_hash'))

    op.drop_table('provider_cache')
    # ### end Alembic commands ###
