"""timeline events

Revision ID: 2f949a969fce
Revises: d1a1f73cd26e
Create Date: 2026-09-23 00:41:23.799910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2f949a969fce'
down_revision: Union[str, None] = 'd1a1f73cd26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_time', sa.String(length=64), nullable=True),
    sa.Column('tz_known', sa.Boolean(), nullable=False),
    sa.Column('certainty', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_timeline_events_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_analysis_id'), ['analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_analysis_id'))

    op.drop_table('timeline_events')
    # ### end Alembic commands ###
