"""retention columns

Revision ID: 19a3b8dca3fa
Revises: 236be77fba57
Create Date: 2026-09-23 02:00:41.878326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19a3b8dca3fa'
down_revision: Union[str, None] = '236be77fba57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kept_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('content_purged_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_calls', schema=None) as batch_op:
        batch_op.drop_column('purged_at')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('content_purged_at')
        batch_op.drop_column('kept_at')

    # ### end Alembic commands ###
