"""text analysis

Revision ID: d240bc2d6315
Revises: 99ea9eb8e350
Create Date: 2026-09-22 18:36:26.666878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd240bc2d6315'
down_revision: Union[str, None] = '99ea9eb8e350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_analysis',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=False),
    sa.Column('normalization_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('language_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('sentence_count', sa.Integer(), nullable=True),
    sa.Column('paragraph_count', sa.Integer(), nullable=True),
    sa.Column('statistics_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('structure_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ai_detection_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_matches_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('embedding_ref', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_text_analysis_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text_analysis')),
    sa.UniqueConstraint('analysis_id', name=op.f('uq_text_analysis_analysis_id'))
    )
    with op.batch_alter_table('text_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_analysis_normalized_sha256'), ['normalized_sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_analysis_normalized_sha256'))

    op.drop_table('text_analysis')
    # ### end Alembic commands ###
