"""image fingerprints

Revision ID: 99ea9eb8e350
Revises: c53b84bc6faf
Create Date: 2026-09-22 16:39:13.908221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '99ea9eb8e350'
down_revision: Union[str, None] = 'c53b84bc6faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_fingerprints',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('md5', sa.String(length=32), nullable=False),
    sa.Column('phash', sa.String(length=16), nullable=False),
    sa.Column('dhash', sa.String(length=16), nullable=False),
    sa.Column('ahash', sa.String(length=16), nullable=False),
    sa.Column('embedding_id', sa.String(length=128), nullable=True),
    sa.Column('algorithm_version', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_image_fingerprints_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_fingerprints')),
    sa.UniqueConstraint('analysis_id', name=op.f('uq_image_fingerprints_analysis_id'))
    )
    with op.batch_alter_table('image_fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_fingerprints_phash'), ['phash'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_fingerprints_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_fingerprints_sha256'))
        batch_op.drop_index(batch_op.f('ix_image_fingerprints_phash'))

    op.drop_table('image_fingerprints')
    # ### end Alembic commands ###
